version: 1.2.{build}

branches:
  only:
  - dev

image: Visual Studio 2022

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: |
      Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
      ./dotnet-install.ps1 -Channel 10.0 -Quality preview
      $env:PATH = "$env:LOCALAPPDATA\Microsoft\dotnet;$env:PATH"

before_build:
  - dotnet --info
  - dotnet restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  include_nuget_references: true
  verbosity: normal

deploy:
- provider: NuGet
  api_key:
    secure: iPtUkccsoDLr8xgpLJMDxVJNZCwEDg/KZCfB/Qjm8EXNO7DCiYYxOCjexaez7Lhp
